class ShortlinksController < ApplicationController
  before_action :set_shortlink, only: [:redirect]
  
  # Form to create new shortlink
  # get /newlink
  def new
    @shortlink = Shortlink.new
  end
  
  #root page
  # get /
  def index
    @shortlinks = Shortlink.paginate(page:params[:page])
  end
  
  #redirect shorturl to longurl
  def redirect
    if @shortlink
      redirect_to @shortlink.longurl
    else
      flash[:error] = "This does not exist"
      redirect_to '/'
    end 
  end 
  
  #show shortlink information (shorturl, longurl)
  # get /shortlinks/:id
  def show
    @shortlink = Shortlink.find(params[:id])
    #debugger
  end
  
  #create shortlink
  # post /newlink
  def create
    @shortlink = Shortlink.new(shortlink_params)
    
    if @shortlink.save
      flash[:success] = "New Short Link has been generated"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  #form to edit shortlink
  #get /shortlinks/:id/edit
  def edit
    @shortlink = Shortlink.find(params[:id])
  end
  
  #update shortlink
  #patch /shortlinks/:id
  def update
    @shortlink = Shortlink.find(params[:id])
    if @shortlink.update_attributes(shortlink_params)
      flash[:success] = "Short link updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  #delete shortlink
  #delete /shortlinks/:id
  def destroy
      Shortlink.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to root_path
  end
  
  #form for sending a shortlink over SMS
  # get /text
  def text
    @shortlink = Shortlink.find(params[:shortid])
  end 
  
  #send message via SMS to provided phone number with link to shortlink
  # post /text
  # message generated by call action in app/services/twilio_text_messenger.rb
  def message
    @shortlink = Shortlink.find(params[:phonenumber][:id])
    @message = "Hi, check out this awesome website: #{request.base_url}/#{@shortlink.shorturl}"
    phonenumber = params[:phonenumber][:phone]
    TwilioTextMessenger.new(@message).call(phonenumber)
    flash[:success] = "Message sent to #{phonenumber}"
    redirect_to root_path
  end
  
  private
    def shortlink_params
      params.require(:shortlink).permit(:shorturl, :longurl)
    end
    
    def set_shortlink
      @shortlink = Shortlink.find_by(shorturl: params[:shortlink])
    end 
end
